function Aup = contract_A_upper(state)

% Compute A^{ij} from A_{ij} using conformal inverse metric:
% A^{ij} = gamma^{ik} gamma^{jl} A_{kl}

[igxx, igxy, igxz, igyy, igyz, igzz] = inverse_metric_3x3( ...
    state.gxx, state.gxy, state.gxz, ...
    state.gyy, state.gyz, state.gzz);

Axx = state.Axx; Axy = state.Axy; Axz = state.Axz;
Ayy = state.Ayy; Ayz = state.Ayz; Azz = state.Azz;

Aup = struct();

Aup.xx = igxx.*(igxx.*Axx + igxy.*Axy + igxz.*Axz) ...
       + igxy.*(igxx.*Axy + igxy.*Ayy + igxz.*Ayz) ...
       + igxz.*(igxx.*Axz + igxy.*Ayz + igxz.*Azz);

Aup.xy = igxx.*(igxy.*Axx + igyy.*Axy + igyz.*Axz) ...
       + igxy.*(igxy.*Axy + igyy.*Ayy + igyz.*Ayz) ...
       + igxz.*(igxy.*Axz + igyy.*Ayz + igyz.*Azz);

Aup.xz = igxx.*(igxz.*Axx + igyz.*Axy + igzz.*Axz) ...
       + igxy.*(igxz.*Axy + igyz.*Ayy + igzz.*Ayz) ...
       + igxz.*(igxz.*Axz + igyz.*Ayz + igzz.*Azz);

Aup.yy = igxy.*(igxy.*Axx + igyy.*Axy + igyz.*Axz) ...
       + igyy.*(igxy.*Axy + igyy.*Ayy + igyz.*Ayz) ...
       + igyz.*(igxy.*Axz + igyy.*Ayz + igyz.*Azz);

Aup.yz = igxy.*(igxz.*Axx + igyz.*Axy + igzz.*Axz) ...
       + igyy.*(igxz.*Axy + igyz.*Ayy + igzz.*Ayz) ...
       + igyz.*(igxz.*Axz + igyz.*Ayz + igzz.*Azz);

Aup.zz = igxz.*(igxz.*Axx + igyz.*Axy + igzz.*Axz) ...
       + igyz.*(igxz.*Axy + igyz.*Ayy + igzz.*Ayz) ...
       + igzz.*(igxz.*Axz + igyz.*Ayz + igzz.*Azz);

end