function Gc = contracted_conformal_connection(state, GammaTilde)

% Compute contracted conformal connection:
%   Gc.x = gamma^{jk} Gamma^x_{jk}
%   Gc.y = gamma^{jk} Gamma^y_{jk}
%   Gc.z = gamma^{jk} Gamma^z_{jk}

[igxx, igxy, igxz, igyy, igyz, igzz] = inverse_metric_3x3( ...
    state.gxx, state.gxy, state.gxz, ...
    state.gyy, state.gyz, state.gzz);

Gc = struct();

Gc.x = igxx .* GammaTilde.xxx ...
     + 2*igxy .* GammaTilde.xxy ...
     + 2*igxz .* GammaTilde.xxz ...
     + igyy .* GammaTilde.xyy ...
     + 2*igyz .* GammaTilde.xyz ...
     + igzz .* GammaTilde.xzz;

Gc.y = igxx .* GammaTilde.yxx ...
     + 2*igxy .* GammaTilde.yxy ...
     + 2*igxz .* GammaTilde.yxz ...
     + igyy .* GammaTilde.yyy ...
     + 2*igyz .* GammaTilde.yyz ...
     + igzz .* GammaTilde.yzz;

Gc.z = igxx .* GammaTilde.zxx ...
     + 2*igxy .* GammaTilde.zxy ...
     + 2*igxz .* GammaTilde.zxz ...
     + igyy .* GammaTilde.zyy ...
     + 2*igyz .* GammaTilde.zyz ...
     + igzz .* GammaTilde.zzz;

end