function [Axx, Axy, Axz, Ayy, Ayz, Azz] = trace_free_A( ...
    Axx, Axy, Axz, Ayy, Ayz, Azz, ...
    gxx, gxy, gxz, gyy, gyz, gzz)

[guxx, guxy, guxz, guyy, guyz, guzz] = inverse_metric_3x3( ...
    gxx, gxy, gxz, gyy, gyz, gzz);

trA = guxx .* Axx ...
    + 2*guxy .* Axy ...
    + 2*guxz .* Axz ...
    + guyy .* Ayy ...
    + 2*guyz .* Ayz ...
    + guzz .* Azz;

one_third_trA = trA / 3.0;

Axx = Axx - one_third_trA .* gxx;
Axy = Axy - one_third_trA .* gxy;
Axz = Axz - one_third_trA .* gxz;
Ayy = Ayy - one_third_trA .* gyy;
Ayz = Ayz - one_third_trA .* gyz;
Azz = Azz - one_third_trA .* gzz;

end